apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# NOTE: Le namespace 'ic-webapp' n'est pas inclus ici car il est
# géré par Terraform.

resources:
  - ebs/ebs-gp3-sc.yml

  - odoo/odoo-secret.yml
  - pgadmin/pg-admin-secret.yml

  - odoo/odoo-pvc.yml
  - pgadmin/pgadmin-pvc.yml

  - odoo/odoo-deployment.yml
  - pgadmin/pg-admin-deployment.yml
  - ic-webapp/ic-webapp-deployment.yml

  - odoo/odoo-clusterip.yml
  - pgadmin/pg_admin-clusterip.yml
  - ic-webapp/ic-webapp-clusterip.yml

  - ingress/alb-ingress.yml