name: CI - Build, Scan, Test Docker & Validate Terraform

on:
  pull_request:
    branches:
      - main

env:
  IMAGE_NAME: ic-webapp
  DOCKERHUB_ID: azeriock
  AWS_REGION: us-east-1
  TF_WORKING_DIR: ./terraform/app

jobs:
  docker-test:
    name: "Docker Build, Scan & Test"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./app
          file: ./app/Dockerfile
          push: false
          tags: ${{ env.DOCKERHUB_ID }}/${{ env.IMAGE_NAME }}:test
          load: true

      - name: Scan image with Snyk
        run: |
          docker run --rm -e SNYK_TOKEN=${{ secrets.SNYK_TOKEN }} \
            -v /var/run/docker.sock:/var/run/docker.sock \
            snyk/snyk:docker snyk test --docker ${{ env.DOCKERHUB_ID }}/${{ env.IMAGE_NAME }}:test || true

      - name: Test container
        run: |
          docker run -d --name test_icwebapp -p 8090:8080 ${{ env.DOCKERHUB_ID }}/${{ env.IMAGE_NAME }}:test
          for i in {1..20}; do
            if curl -s -f http://localhost:8090 >/dev/null; then
              docker rm -f test_icwebapp
              exit 0
            fi
            sleep 3
          done
          docker rm -f test_icwebapp
          exit 1

  terraform-test:
    name: "Terraform Lint, Validate & Plan (PR)"
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      #- name: Configure AWS credentials via OIDC
      #  uses: aws-actions/configure-aws-credentials@v4
      #  with:
      #    role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}
      #    aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.0"

      - name: Terraform Format Check
        run: terraform fmt -check -diff
        working-directory: ${{ env.TF_WORKING_DIR }}

      - name: Terraform Init
      #backend a remettre ensuite
        run: terraform init -backend =false
        working-directory: ${{ env.TF_WORKING_DIR }}

      - name: Terraform Validate
        run: terraform validate
        working-directory: ${{ env.TF_WORKING_DIR }}

      #- name: Terraform Plan
      #  run: terraform plan -no-color
      #  env:
      #    TF_VAR_cicd_iam_role_arn: ${{ secrets.AWS_IAM_ROLE_ARN }}
      #    TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
      #  working-directory: ${{ env.TF_WORKING_DIR }}