name: CD - Deploy to EKS

on:
  workflow_dispatch:
#on:
  # Se déclenche à la fin de l'exécution du workflow de CI
#  workflow_run:
    # Nom du workflow de CI (défini dans le fichier ci.yml)
#    workflows: ["CI - Build, Scan, Test and Push Docker Image"]
#    types:
#      - completed
#    branches: [main]

env:
  AWS_REGION: us-east-1
  EKS_CLUSTER_NAME: main-cluster

jobs:
  deploy:
    if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'push'
    permissions:
      id-token: write 
      contents: read  
    environment:
      name: production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }} 
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform/app

      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          TF_VAR_cicd_iam_role_arn: ${{ secrets.AWS_IAM_ROLE_ARN }}
          TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
        working-directory: ./terraform/app

      - name: Configure kubectl for EKS
        run: aws eks update-kubeconfig --name ${{ env.EKS_CLUSTER_NAME }} --region ${{ env.AWS_REGION }}

      - name: Deploy Kubernetes Manifests
        env:
          PGADMIN_PASSWORD: ${{ secrets.PGADMIN_PASSWORD }}
        run: |
          echo "PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}" > ./kubernetes/pgadmin.env
          echo "Applying all Kubernetes manifests with Kustomize..."
          kubectl apply -k ./kubernetes
          rm -f ./kubernetes/pgadmin.env
